### ISSUE TITLE
compile_native_go_fuzzer problem calling functions from another file in same package

### ISSUE THREAD

**Issue by hickford** [AdamKorcz/go-118-fuzz-build#2]
My tests call functions from other files in the same package. compile_native_go_fuzzer seems to have a problem with this -- during the "replacing *testing.F"  step I see undefined errors:

    testonly/tree_fuzz_test.go_fuzz_.go:30:11: undefined: newTree

Example https://github.com/transparency-dev/merkle/runs/7502903729?check_suite_focus=true via https://github.com/transparency-dev/merkle/pull/36

**Comment by AdamKorcz** [comment]
Try doing this in build.sh:

`mv testonly/tree_test.go testonly/tree_test_fuzz.go` before running `compile_native_go_fuzzer`.

**Comment by hickford** [comment]
Ooh that fixes some of the errors but there's functions from other files such as `reference_test.go` needed too. Any suggestions?

**Comment by AdamKorcz** [comment]
> Ooh that fixes some of the errors but there's functions from other files such as `reference_test.go` needed too. Any suggestions?

Yeah, you can do the same for all `_test.go` files.

**Comment by hickford** [comment]
I'm confused. Surely the second move command will overwrite the result of the first? Am I missing something?
 
```
mv testonly/constants.go        testonly/tree_test_fuzz.go
mv testonly/reference_test.go   testonly/tree_test_fuzz.go
mv testonly/tree_test.go        testonly/tree_test_fuzz.go
mv testonly/tree.go             testonly/tree_test_fuzz.go
compile_native_go_fuzzer github.com/transparency-dev/merkle/testonly FuzzConsistencyProofAndVerify FuzzConsistencyProofAndVerify
compile_native_go_fuzzer github.com/transparency-dev/merkle/testonly FuzzInclusionProofAndVerify FuzzInclusionProofAndVerify
compile_native_go_fuzzer github.com/transparency-dev/merkle/testonly FuzzHashAtAgainstReferenceImplementation FuzzHashAtAgainstReferenceImplementation
compile_native_go_fuzzer github.com/transparency-dev/merkle/testonly FuzzInclusionProofAgainstReferenceImplementation FuzzInclusionProofAgainstReferenceImplementation
compile_native_go_fuzzer github.com/transparency-dev/merkle/testonly FuzzConsistencyProofAgainstReferenceImplementation FuzzConsistencyProofAgainstReferenceImplementation
```

**Comment by hickford** [comment]
I realise this is an issue in the [compile_native_go_fuzzer](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_native_go_fuzzer) script rather than this library . Shall I create a new issue in oss-fuzz?

**Comment by AdamKorcz** [comment]
> I realise this is an issue in the [compile_native_go_fuzzer](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile_native_go_fuzzer) script rather than this library . Shall I create a new issue in oss-fuzz?

Could you elaborate on what the issue is?

**Comment by AdamKorcz** [comment]
> I'm confused. Surely the second move command will overwrite the result of the first? Am I missing something?

Sorry I missed this one. You are correct, you should not name all files `testonly/tree_test_fuzz.go`.  It would be:

`mv testonly/reference_test.go   testonly/reference_test_fuzz.go`

**Comment by hickford** [comment]
Thanks, that worked. What's going on? Only files with 'fuzz' in the name are copied?
