### ISSUE TITLE
Symbol from a different _test.go file

### ISSUE THREAD

**Issue by pkillarjun** [AdamKorcz/go-118-fuzz-build#25]
Build failed [log](https://oss-fuzz-build-logs.storage.googleapis.com/log-81f25874-a254-40ed-b129-ec0ac7c4a0b8.txt).

`newTestMessageFromRFC822()` is in [build_framework_test.go](https://github.com/ProtonMail/proton-bridge/blob/61ca604acebcc861d9cc1ac5b98041de299593c1/pkg/message/build_framework_test.go#L96), but it's needed by `TestHeaderOrder()` in [header_test.go](https://github.com/ProtonMail/proton-bridge/blob/61ca604acebcc861d9cc1ac5b98041de299593c1/pkg/message/header_test.go#L139).

Is there any plan to support this somehow, or should I rely on hacks?

**Comment by AdamKorcz** [comment]
I think this is already fixed in the november-backup branch of this repository, but there might still be edge cases it doesn't cover. I can test it out on proton-bridge.
