### ISSUE TITLE
Removing vitess to further removing dependencies

### ISSUE THREAD

**Issue by kzys** [AdamKorcz/go-118-fuzz-build#4]
Currently this modules' go.mod is having Vitess, but it is only used by https://github.com/AdamKorcz/go-118-fuzz-build/tree/main/fuzzers/vitess. The projects that could consume this package through compile_native_go_fuzzer wouldn't need Vitess to have fuzzing.

What do you think?

**Comment by AdamKorcz** [comment]
I am fine with removing fuzzers/vitess from this repo. Wanna create a PR?

**Comment by kzys** [comment]
Sure. After #3 :)
