### ISSUE TITLE
Support t.Skip in the testing.T type

### ISSUE THREAD

**Issue by howardjohn** [AdamKorcz/go-118-fuzz-build#6]
Example why we use it: https://github.com/istio/istio/blob/8315394ad96aecb83c33bac225041a0106d6ea33/pkg/fuzz/README.md#L16

Workaround we are using now: (TODO)

**Comment by howardjohn** [comment]
Workaround: https://github.com/istio/istio/pull/40989

**Comment by AdamKorcz** [comment]
This is now supported in https://github.com/AdamKorcz/go-118-fuzz-build/tree/main/testing
